name: Docker

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Stage artifacts
        run: |
            docker build . --file Dockerfile -t mohameddev006/web-app:latest
            docker login -u ${{ secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_PASS}}
            docker push mohameddev006/web-app:latest
